### ISSUE TITLE
 CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by XinyueZ** [Harry-Zhi/semantic_nerf#27]
```
 home/xxxx/.conda/envs/semantic_nerf/lib/python3.7/site-packages/torch/nn/functional.py:3121: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/xxxx/.conda/envs/semantic_nerf/lib/python3.7/site-packages/torch/cuda/__init__.py:125: UserWarning: 
NVIDIA GeForce RTX 3070 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the NVIDIA GeForce RTX 3070 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
prepare rays
prepare rays
prepare rays
Begin
  0%|                                                                                                                                                                                                  | 0/200001 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_SSR_main.py", line 224, in <module>
    train()
  File "train_SSR_main.py", line 212, in train
    ssr_trainer.step(global_step)
  File "/home/xxxx/Desktop/work/semantic_nerf/SSR/training/trainer.py", line 882, in step
    sampled_data = self.sample_data(global_step, self.rays, self.H, self.W, no_batching=True, mode="train")
  File "/home/xxxx/Desktop/work/semantic_nerf/SSR/training/trainer.py", line 650, in sample_data
    sampled_rays = rays[index_batch, index_hw, :]
RuntimeError: CUDA error: no kernel image is available for execution on the device

```

**Comment by Harry-Zhi** [comment]
Hi @Harry-Zhi, 

Could you please double check if CUDA-enabled pytorch is successfully installed? If so,  probably you could try to change the device id or specifically set the GPU device explicitly via bash. It should work well given GPUs and pytorch.

Please let me know if you have any further questions.

**Comment by XinyueZ** [comment]
thank you @Harry-Zhi I think this is bc of setup my machine, I close this issue.
